name: Typechecking and linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy
          pip install -r requirements.txt
      - name: Format with black
        run: |
          black --check .
      - name: Typecheck with mypy
        run: |
          mypy --strict watsong/
      - name: Test python unit tests
        run: |
          source envs/dev-unix.sh
          python -m unittest
      - name: Run integration tests
        run: |
          source envs/dev-unix.sh
          pytest
